from.browser_decorator import browser,AsyncQueueResult

from botasaurus_driver.driver import Driver,Wait,IframeElement
from botasaurus_driver.exceptions import DriverException,GoogleCookieConsentException,IframeNotFoundException,ElementWithTextNotFoundException,ElementWithSelectorNotFoundException,InputElementForLabelNotFoundException,CheckboxElementForLabelNotFoundException,PageNotFoundException,CloudflareDetectionException,ElementInitializationException,DetachedElementException,ElementPositionNotFoundException,ElementPositionException,ElementScreenshotException,ScreenshotException,InvalidFilenameException,ChromeException,JavascriptException,JavascriptSyntaxException,JavascriptRuntimeException
from botasaurus_driver import cdp